### ISSUE TITLE
CameraRoll.saveToCameraRoll saves animated gif as static images

### ISSUE THREAD

**Issue by cpojer** [react-native-cameraroll/react-native-cameraroll#16] opened 2019-03-19 12:54 UTC
* * *
  This issue was originally created by @mferranti as facebook/react-native#16223.
  * * *

  

### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes
### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  8.4.0
    Yarn:  Not Found
    npm:  5.3.0
    Watchman:  4.5.0
    Xcode:  Xcode 9.0 Build version 9A235
    Android Studio:  Not Found

    Packages:
      react: 16.0.0-alpha.12
      react-native: 0.47.2
    
   Target Platform: iOS (10.3)

### Steps to Reproduce

(Write your steps here:)

1. Create new project
2. Save a gif with camera roll. `CameraRoll.saveToCameraRoll('https://k60.kn3.net/B/1/5/9/2/D/971.gif');`

### Expected Behavior

The gif should be animated.

### Actual Behavior

The gif was saved in photo album but is an static image. It hasn't got animation and only the first frame is shown.
Maybe is related with #16117
 
### Reproducible Demo

  Here is an example code to reproduce. But snack does not allow to see the images of the device. I think.
  https://snack.expo.io/BkAe8yE2Z

**Comment by StevenMasini** [comment] 2019-03-20 03:07
Just adding the link

> Maybe is related with [#16117](
https://github.com/facebook/react-native/issues/16117)

**Comment by erandagan** [comment] 2019-03-21 14:27
The bug is caused by the camera roll manager loading the input URI into a UIImage [here.](https://github.com/react-native-community/react-native-cameraroll/blob/9540b013d34356b53f4c6346575eefc41794bbc3/ios/RNCCameraRollManager.m#L139) 

Calling [`creationRequestForAssetFromImageAtFileURL`](https://developer.apple.com/documentation/photokit/phassetchangerequest/1624059-creationrequestforassetfromimage?language=objc) with the input URI works as expected with animated GIFs, but has the limitation of only supporting `file://` URIs.

**Comment by littletower** [comment] 2019-11-29 08:45
Support for gifs would be awesome, did anyone find a workaround in the meantime?

**Comment by satorusasozaki** [comment] 2020-06-11 22:56
+1

**Comment by Mavenic** [comment] 2020-06-21 13:07
Any solution or workaround for this?

**Comment by Arjan-Zuidema** [comment] 2022-09-30 12:58
This should now be fixed in 5.0.3. Feel free to reopen when it's still a problem

**Closed by Arjan-Zuidema** 2022-09-30 12:58 UTC
Labels: bug, help wanted
