### ISSUE TITLE
AndroidManifest.xml missing package after one successful build.

### ISSUE THREAD

**Issue by Senior-Code** [react-native-cameraroll/react-native-cameraroll#514] opened 2023-07-15 08:06 UTC
Hi I do not really understand what is going on, but after I install the package and build (for debug or generate signed app), after one successful build, android build error with this message 
<img width="706" alt="253728535-b39498f8-109f-4241-a86a-33f74604be4d" src="https://github.com/react-native-cameraroll/react-native-cameraroll/assets/42084438/46c94a02-8d64-4bc9-9dc4-d14b7b858e40">
I just found out that the AndroidManifest.xml file is missing package.
<img width="610" alt="image" src="https://github.com/react-native-cameraroll/react-native-cameraroll/assets/42084438/f9fd9bc3-2616-4fac-a3ac-699560ca477b">
Even, I overwrite the file, it will be missing again after one successful build.

react native version 0.70.11
react-native camera-roll lastest

**Comment by Senior-Code** [comment] 2023-07-17 07:04
Hi I do not really understand what is going on, but after I install the package and build (for debug or generate signed app), after one successful build, android build error with this message 
<img width="706" alt="253728535-b39498f8-109f-4241-a86a-33f74604be4d" src="https://github.com/react-native-cameraroll/react-native-cameraroll/assets/42084438/46c94a02-8d64-4bc9-9dc4-d14b7b858e40">
I just found out that the AndroidManifest.xml file is missing package.
<img width="610" alt="image" src="https://github.com/react-native-cameraroll/react-native-cameraroll/assets/42084438/f9fd9bc3-2616-4fac-a3ac-699560ca477b">
Even, I overwrite the file, it will be missing again after one successful build.

**Comment by somasekharkakarla** [comment] 2023-07-19 13:53
i am also facing same issue
 "@react-native-camera-roll/camera-roll": "^5.7.2",
"react-native": "0.70.5",

**Comment by Farhandroid** [comment] 2023-07-21 03:39
I have also faced this issue. I think RN has an issue with reading the folder alphabetically. So I have created a dummy folder named "aaa" and put the AndroidManifest.xml with the package name there. After that, the project was built successfully.

![362229479_3365431240336875_1698742052812160171_n](https://github.com/react-native-cameraroll/react-native-cameraroll/assets/32593150/5836a62b-2276-4d21-afa4-0d0c16db82b4)

**Comment by Arjan-Zuidema** [comment] 2023-07-21 08:34
Try using 5.6.0 when using older versions of react-native than 73. Version 5.7.0 and above only add support for react-native 73.

**Comment by somasekharkakarla** [comment] 2023-07-24 15:47
@Arjan-Zuidema  React native 0.73? it is still no released. you mean 0.72?

**Comment by Senior-Code** [comment] 2023-07-28 07:56
> Try using 5.6.0 when using older versions of react-native than 73. Version 5.7.0 and above only add support for react-native 73.

still not work.

**Comment by Senior-Code** [comment] 2023-07-28 07:59
> I have also faced this issue. I think RN has an issue with reading the folder alphabetically. So I have created a dummy folder named "aaa" and put the AndroidManifest.xml with the package name there. After that, the project was built successfully.
> 
> ![362229479_3365431240336875_1698742052812160171_n](https://user-images.githubusercontent.com/32593150/255066362-5836a62b-2276-4d21-afa4-0d0c16db82b4.jpg)

did you have to config anything in build.gradle as well ?

**Comment by wizebin** [comment] 2023-08-15 16:37
Looks like the build.gradle file has code specifically to remove the package prop 

https://github.com/react-native-cameraroll/react-native-cameraroll/blob/08f172ff57c5818d89141ccd179d20f6c77bb7af/android/build.gradle#L116C1-L135C39

coming from this commit

https://github.com/react-native-cameraroll/react-native-cameraroll/commit/2e4851eae72913cb1ed543df58a929a9e5ec115f

As you can see here the build.gradle removes the package property if the agpVersion is > 7

I used patch-package to remove the highlighted code in this link since I don't have time to research the reason behind it, I'm sure one of the maintainers will have a better understanding, removing the code resolves this problem for me since I'm using a newer version of the agp and an older version of react native (68.2)

**Comment by Arjan-Zuidema** [comment] 2023-08-23 07:14
> @Arjan-Zuidema React native 0.73? it is still no released. you mean 0.72?

No I mean 0.73. Which is not released, but it is recommended for package maintainers to apply this fix

**Comment by mattjbrill** [comment] 2023-08-23 22:02
> > @Arjan-Zuidema React native 0.73? it is still no released. you mean 0.72?
> 
> No I mean 0.73. Which is not released, but it is recommended for package maintainers to apply this fix

So the let's get ready for 73 update checks the agp version
https://github.com/react-native-cameraroll/react-native-cameraroll/blob/08f172ff57c5818d89141ccd179d20f6c77bb7af/android/build.gradle#L117

but the proposal for 73 (https://github.com/react-native-community/discussions-and-proposals/issues/671) says `0.73 will depend on Android Gradle Plugin (AGP) 8.x.`.

Should the `def shouldUseNameSpace = agpVersion >= 7` line be `def shouldUseNameSpace = agpVersion >= 8` instead?

**Comment by Arjan-Zuidema** [comment] 2023-08-24 14:37
If you check all the pull requests and commits referenced in the proposal all the checks are the same. So why would it not work here but all the other packages?
Also, it works fine here and I cannot reproduce the error.

**Comment by mattjbrill** [comment] 2023-08-24 20:01
Ahh I see what you mean. Yes, that does seem to be an appropriate resolution for new installs.

Still, I was having issues that were resolved by changing that AGP check to eight or later, so what you said got me curious, and I started clicking through a couple of the mentions in there. Some do match what has been done here. Others (random sample here, I did not click through all the mentions) have instead opted to not modify the `AndroidManifest.xml`, but include the `namespace`:
https://github.com/software-mansion/react-native-gesture-handler/pull/2448/files
https://github.com/zoontek/react-native-permissions/pull/782/files
https://github.com/zoontek/react-native-bootsplash/pull/462#issuecomment-1606014020
https://github.com/mkuczera/react-native-haptic-feedback/pull/105/files
https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1598892444

Namespace has been ["Available since AGP 4.2.0-beta03."](https://issuetracker.google.com/issues/200682321#comment3), but only required since ["AGP 8.0.0-alpha03"](https://issuetracker.google.com/issues/200682321#comment13). I haven't dug around a ton, but it looks like having a package name doesn't cause problems ["AGP 7.3 - Warn if a package attribute is found in the source manifest."](https://issuetracker.google.com/issues/172361895#comment1). It sounds like not removing the package name, and adding the namespace, allows for backwards compatibility. But, as I said, I did not dig much, so leaving the package name in may cause issues in the future. I do not know.

For @Senior-Code , @somasekharkakarla, and anyone else that are running react native <= 0.69.x, not using react native fabric, and/or (I'm honestly not sure) targeting android sdk < 33 (or maybe 31?), you can try [patching](https://github.com/ds300/patch-package) 5.7.2 to swap that 7 to an 8 like I mentioned above, or you can [delete this block](https://github.com/react-native-cameraroll/react-native-cameraroll/blob/08f172ff57c5818d89141ccd179d20f6c77bb7af/android/build.gradle#L116-L135) and add [this](https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1598892444) to the `android {}` block in the `android/build.gradle` file.

Apologies for arguing! My intention was to help the others experiencing the same issue I had faced. I'll pipe down, and leave things to the collaborators.

Thanks for keeping this camera roll rolling! Appreciate it! :)

**Comment by Arjan-Zuidema** [comment] 2023-08-25 08:24
> Ahh I see what you mean. Yes, that does seem to be an appropriate resolution for new installs.
> 
> Still, I was having issues that were resolved by changing that AGP check to eight or later, so what you said got me curious, and I started clicking through a couple of the mentions in there. Some do match what has been done here. Others (random sample here, I did not click through all the mentions) have instead opted to not modify the `AndroidManifest.xml`, but include the `namespace`: https://github.com/software-mansion/react-native-gesture-handler/pull/2448/files https://github.com/zoontek/react-native-permissions/pull/782/files [zoontek/react-native-bootsplash#462 (comment)](https://github.com/zoontek/react-native-bootsplash/pull/462#issuecomment-1606014020) https://github.com/mkuczera/react-native-haptic-feedback/pull/105/files [react-native-community/discussions-and-proposals#671 (comment)](https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1598892444)

Maybe we can add the namespace back in the manifest file. You think that would fix the problems?

> Namespace has been ["Available since AGP 4.2.0-beta03."](https://issuetracker.google.com/issues/200682321#comment3), but only required since ["AGP 8.0.0-alpha03"](https://issuetracker.google.com/issues/200682321#comment13). I haven't dug around a ton, but it looks like having a package name doesn't cause problems ["AGP 7.3 - Warn if a package attribute is found in the source manifest."](https://issuetracker.google.com/issues/172361895#comment1). It sounds like not removing the package name, and adding the namespace, allows for backwards compatibility. But, as I said, I did not dig much, so leaving the package name in may cause issues in the future. I do not know.

I did not investigate much either, just read some things in the proposal and looked what others did. Like I said above, we can add back the namespace in the manifest for backward compatibility. And remove it again when it really becomes a problem.

> For @Senior-Code , @somasekharkakarla, and anyone else that are running react native <= 0.69.x, not using react native fabric, and/or (I'm honestly not sure) targeting android sdk < 33 (or maybe 31?), you can try [patching](https://github.com/ds300/patch-package) 5.7.2 to swap that 7 to an 8 like I mentioned above, or you can [delete this block](https://github.com/react-native-cameraroll/react-native-cameraroll/blob/08f172ff57c5818d89141ccd179d20f6c77bb7af/android/build.gradle#L116-L135) and add [this](https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1598892444) to the `android {}` block in the `android/build.gradle` file.
> 
> Apologies for arguing! My intention was to help the others experiencing the same issue I had faced. I'll pipe down, and leave things to the collaborators.

Nah, it's not arguing it's good someone looks at it with a different view 🙂 This way we can come up with possible fixes.

> Thanks for keeping this camera roll rolling! Appreciate it! :)

**Comment by mattjbrill** [comment] 2023-08-30 20:34
Hey! Apologies for the delay. Got wrapped up in other work, and have not had a chance to test anything out with this package. If I come up with anything, I'll put in a PR. Don't hold your breath though! Might be a while :)

Thanks again for everything! Appreciate everyone's time & efforts that they've dedicated to this project.

**Comment by Arjan-Zuidema** [comment] 2023-11-07 11:09
This should now be fixes in [v6.0.2](https://github.com/react-native-cameraroll/react-native-cameraroll/releases/tag/v6.0.2)

**Closed by Arjan-Zuidema** 2023-11-07 11:09 UTC
