### ISSUE TITLE
Unrecognized generic type 'SubTypes' in NativeModule spec

### ISSUE THREAD

**Issue by dancixx** [react-native-cameraroll/react-native-cameraroll#498] opened 2023-06-11 06:54 UTC
Hi guys

I got this error when try to install pods with new arch.

```
System:
  OS: macOS 13.4
  CPU: (10) arm64 Apple M1 Pro
  Memory: 385.67 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.18.1
    path: ~/.nvm/versions/node/v16.18.1/bin/node
  Yarn:
    version: 1.22.18
    path: /usr/local/bin/yarn
  npm:
    version: 9.6.3
    path: ~/.nvm/versions/node/v16.18.1/bin/npm
  Watchman:
    version: 2023.05.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/danixx/.rvm/rubies/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/danixx/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0-rc.5
    wanted: ^0.72.0-rc.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

```
UnsupportedGenericParserError: Module NativeCameraRollModule: Unrecognized generic type 'SubTypes' in NativeModule spec.
    at translateTypeReferenceAnnotation (/Users/danixx/Desktop/connec-fitness-rn/node_modules/@react-native/codegen/lib/parsers/typescript/modules/index.js:153:15)
    at translateTypeAnnotation (/Users/danixx/Desktop/connec-fitness-rn/node_modules/@react-native/codegen/lib/parsers/typescript/modules/index.js:224:14)
    at parseObjectProperty (/Users/danixx/Desktop/connec-fitness-rn/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:261:7)
    at /Users/danixx/Desktop/connec-fitness-rn/node_modules/@react-native/codegen/lib/parsers/typescript/modules/index.js:61:16
    at guard (/Users/danixx/Desktop/connec-fitness-rn/node_modules/@react-native/codegen/lib/parsers/utils.js:26:14)
    at /Users/danixx/Desktop/connec-fitness-rn/node_modules/@react-native/codegen/lib/parsers/typescript/modules/index.js:60:14
    at Array.map (<anonymous>)
    at translateObjectTypeAnnotation (/Users/danixx/Desktop/connec-fitness-rn/node_modules/@react-native/codegen/lib/parsers/typescript/modules/index.js:59:6)
    at translateTypeAnnotation (/Users/danixx/Desktop/connec-fitness-rn/node_modules/@react-native/codegen/lib/parsers/typescript/modules/index.js:320:14)
    at parseObjectProperty (/Users/danixx/Desktop/connec-fitness-rn/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:261:7) {
  nodes: [
    Node {
      type: 'TSTypeReference',
      start: 414,
      end: 422,
      loc: SourceLocation {
        start: Position { line: 16, column: 14, index: 414 },
        end: Position { line: 16, column: 22, index: 422 },
        filename: undefined,
        identifierName: undefined
      },
      typeName: Node {
        type: 'Identifier',
        start: 414,
        end: 422,
        loc: SourceLocation {
          start: Position { line: 16, column: 14, index: 414 },
          end: Position { line: 16, column: 22, index: 422 },
          filename: undefined,
          identifierName: 'SubTypes'
        },
        name: 'SubTypes'
      }
    }
  ]
}
Error: Command failed: node /Users/danixx/Desktop/connec-fitness-rn/node_modules/@react-native/codegen/lib/cli/combine/combine-js-to-schema-cli.js --platform ios /var/folders/gj/zdd7mjxx5t98dvcc82k72kdc0000gn/T/rncamerarollZj293L/schema.json /Users/danixx/Desktop/connec-fitness-rn/node_modules/@react-native-camera-roll/camera-roll/src
/Users/danixx/Desktop/connec-fitness-rn/node_modules/flow-parser/flow_parser.js:818
throw a}function
```

**Comment by Arjan-Zuidema** [comment] 2023-06-21 09:03
Hi! What command are you using to install the pods?

**Comment by dancixx** [comment] 2023-06-21 22:55
@Arjan-Zuidema `RCT_NEW_ARCH_ENABLED=1 USE_FABRIC=1 install --repo-update`

**Comment by ken0x0a** [comment] 2023-06-22 03:29
I got the same error with "react-native@0.72.0" & "@react-native/codegen@0.72.6"

**Comment by johnf** [comment] 2023-06-22 04:20
I think it's hitting this bug
https://github.com/facebook/react-native/issues/36431
If I paste the SubType definition into `NativeCameraRoll.ts' instead of using the import it seems to compile OK

**Comment by Arjan-Zuidema** [comment] 2023-06-22 06:46
@johnf I am unable to reproduce the error, but [this](https://github.com/Arjan-Zuidema/react-native-cameraroll/commit/286a0eb8eeb56cd6971bd9ac6f29c459a0d87ab2) fixes it for you? If so, I can merge this

**Comment by johnf** [comment] 2023-06-22 22:39
@Arjan-Zuidema https://github.com/react-native-cameraroll/react-native-cameraroll/pull/501 works for me.
Not great as it duplicates the type.
Note: I only hit this when turning on new arch

**Comment by johnf** [comment] 2023-06-23 00:53
OK ignore this. Was user error on my part.

If you have the same issue, make sure you don't have `react-native-codegen` as a dependency. The new package is `@rect-native/codegen' but you shouldn't need it at all as react native already depends on it.

**Comment by Arjan-Zuidema** [comment] 2023-06-23 07:05
So there is no issue and we can close this?

**Comment by santhoshvai** [comment] 2023-06-23 09:05
@Arjan-Zuidema I think we can close this.. in 0.72 docs we can see that the codegen package has moved to a new namespace

**Closed** 2023-06-23 09:07 UTC

**Comment by dancixx** [comment] 2023-07-01 07:47
Error still occurs.

**Comment by billnbell** [comment] 2023-07-04 00:06
I am getting this as well.

**Comment by johnf** [comment] 2023-07-04 00:23
@Arjan-Zuidema This actually needs to be reopened. I was changing so many things, I forgot I had turned off new arch when I thought this was fixed.
Let me know if you want me to create a reproducible repo
I have a PR with a "fix"

**Comment by billnbell** [comment] 2023-07-04 01:22
this fixes for me https://github.com/react-native-cameraroll/react-native-cameraroll/issues/511#issuecomment-1617810859

**Comment by Arjan-Zuidema** [comment] 2023-07-04 08:29
I just published 5.7.2 which should fix the issue. Can you confirm?

**Comment by johnf** [comment] 2023-07-04 22:39
@Arjan-Zuidema Looks good here. Thanks!

**Comment by billnbell** [comment] 2023-07-05 04:15
it works!
