### ISSUE TITLE
Task :react-native-camera-roll_camera-roll:packageDebugResources FAILED

### ISSUE THREAD

**Issue by SuHangWeb** [react-native-cameraroll/react-native-cameraroll#624] opened 2024-05-07 08:21 UTC
Configure project :react-native-reanimated
Android gradle plugin: 8.1.1
Gradle: 8.3

> Configure project :react-native-vision-camera
[VisionCamera] react-native-worklets-core not found, Frame Processors disabled!

> Task :@react-native-camera-roll_camera-roll:compileDebugJavaWithJavac

> Task :react-native-camera-roll_camera-roll:packageDebugResources FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
45 actionable tasks: 38 executed, 7 up-to-date

**Comment by Arjan-Zuidema** [comment] 2024-05-07 08:22
Duplicate of #623

**Closed by Arjan-Zuidema** 2024-05-07 08:22 UTC
