### ISSUE TITLE
MIME type video/mp4 cannot be inserted

### ISSUE THREAD

**Issue by SHRASHRI08** [react-native-cameraroll/react-native-cameraroll#499] opened 2023-06-12 15:41 UTC
MIME type video/mp4 cannot be inserted into content expected MIME type under image/*

Getting this error even after taking the latest update

**Comment by Arjan-Zuidema** [comment] 2023-06-22 06:47
What function are you calling when this error occurs?

**Comment by SHRASHRI08** [comment] 2023-07-10 05:49
await CameraRoll.save(outputVideoPath, 'video')
                  .then(() => {
                    Alert.alert(
                      'Download successful',
                      `${fileName} saved to gallery`,
                      [{
                        text: 'OK', onPress: () => insertVideo()
                      }],
                      { cancelable: false }
                    );
                  })

This is the function

**Comment by SHRASHRI08** [comment] 2023-07-10 07:07
Extremely annoyed by this error, 
It only appears in android API Level >=30

**Comment by SHRASHRI08** [comment] 2023-07-10 11:32
Any update on this ?

**Comment by MinhThu100200** [comment] 2023-07-14 09:06
Any update ?

**Comment by Arjan-Zuidema** [comment] 2023-07-14 11:47
Duplicate of #423

**Closed by Arjan-Zuidema** 2023-07-14 11:47 UTC
