### ISSUE TITLE
Cannot compare java.lang.String with value '0.72.6' and java.lang.Integer with value '71'

### ISSUE THREAD

**Issue by UNIDY2002** [react-native-cameraroll/react-native-cameraroll#555] opened 2023-11-07 10:50 UTC
This line is causing the APP to fail to build:
https://github.com/react-native-cameraroll/react-native-cameraroll/blob/17e1fe28438258a7e99bbe0b547e01562a363928/android/build.gradle#L117

See this action:
https://github.com/thu-info-community/thu-info-app/actions/runs/6782603847/job/18435230133?pr=484#step:8:109

**Comment by Arjan-Zuidema** [comment] 2023-11-07 10:52
Duplicate of #554

**Closed by Arjan-Zuidema** 2023-11-07 10:52 UTC
