### ISSUE TITLE
Execution failed for task ':@react-native-camera-roll_camera-roll:generateDebugRFile' React native 0.71.8

### ISSUE THREAD

**Issue by DeveloperMCD** [react-native-cameraroll/react-native-cameraroll#520] opened 2023-08-12 11:04 UTC
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':@react-native-camera-roll_camera-roll:generateDebugRFile'.
> A failure occurred while executing com.android.build.gradle.internal.res.GenerateLibraryRFileTask$GenerateLibRFileRunnable
   > /home/matthew/.gradle/caches/transforms-3/bf85159ad0b7b35e903c7e20ebad4883/transformed/com.facebook.react-r.txt

    at makeError (/home/matthew/dev/rn/stackbayapp/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /home/matthew/dev/rn/stackbayapp/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (/home/matthew/dev/rn/stackbayapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)
    at async Command.handleAction (/home/matthew/dev/rn/stackbayapp/node_modules/@react-native-community/cli/build/index.js:108:9)

Package.json:
        "@bam.tech/react-native-make": "^3.0.3",
        "@fortawesome/fontawesome-svg-core": "^6.4.0",
        "@fortawesome/free-regular-svg-icons": "^6.4.0",
        "@fortawesome/free-solid-svg-icons": "^6.4.0",
        "@fortawesome/react-native-fontawesome": "^0.3.0",
        "@react-native-async-storage/async-storage": "^1.18.2",
        "@react-native-camera-roll/camera-roll": "^5.7.2",
        "@react-native-community/cli-platform-ios": "^11.3.6",
        "@react-native-community/geolocation": "^3.0.6",
        "@react-native-masked-view/masked-view": "^0.2.9",
        "@react-navigation/native": "^6.1.7",
        "@react-navigation/native-stack": "^6.9.12",
        "@react-navigation/stack": "^6.3.16",
        "@reduxjs/toolkit": "^1.9.5",
        "fbjs": "^3.0.5",
        "react": "18.2.0",
        "react-native": "0.71.8",
        "react-native-background-actions": "^3.0.0",
        "react-native-fontawesome": "^7.0.0",
        "react-native-gesture-handler": "^2.10.1",
        "react-native-modal": "^13.0.1",
        "react-native-orientation": "^3.1.3",
        "react-native-paper": "^5.9.1",
        "react-native-paper-dropdown": "^1.0.7",
        "react-native-reanimated": "^2.10.0",
        "react-native-safe-area-context": "^4.7.1",
        "react-native-scan-barcode": "^3.1.7",
        "react-native-screens": "^3.20.0",
        "react-native-sound": "^0.11.2",
        "react-native-svg": "^13.9.0",
        "react-native-vector-icons": "^10.0.0",
        "react-native-vision-camera": "^2.15.4",
        "react-redux": "^8.0.5",
        "react-usestateref": "^1.0.8",
        "vision-camera-code-scanner": "^0.2.0"

**Comment by YahyaBagia** [comment] 2023-08-21 10:46
I have the same issue. Were you able to fix it somehow?

**Comment by Arjan-Zuidema** [comment] 2023-09-12 13:11
@DeveloperMCD Can you provide a minimal reproducible repo? I can't seem to reproduce it

**Comment by sriramadari** [comment] 2023-09-16 06:20
How can  I fix this , help me out :

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :@react-native-camera-roll_camera-roll.
     Required by:
         project :app
      > No matching configuration of project :@react-native-camera-roll_camera-roll was found. The consumer was configured to find a component for use during compile-time, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.ProductFlavor:react-native-camera' with value 'general', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.4.2' but:
          - None of the consumable configurations have attributes.

**Comment by mateomarconi** [comment] 2023-09-21 17:32
I am having the same issue after upgrade to ReactNative 0.72.4.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@react-native-camera-roll_camera-roll:generateDebugRFile'.
> Could not resolve all files for configuration ':@react-native-camera-roll_camera-roll:debugCompileClasspath'.
   > Could not find com.facebook.react:react-native:0.72.4.
     Required by:
         project :@react-native-camera-roll_camera-roll

```

**Comment by mihailapuste** [comment] 2023-09-22 20:23
Getting the same error as @mateomarconi. Wondering if there any updates/workaround solutions. Thanks!

**Comment by mihailapuste** [comment] 2023-09-22 23:07
> I am having the same issue after upgrade to ReactNative 0.72.4.
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':@react-native-camera-roll_camera-roll:generateDebugRFile'.
> > Could not resolve all files for configuration ':@react-native-camera-roll_camera-roll:debugCompileClasspath'.
>    > Could not find com.facebook.react:react-native:0.72.4.
>      Required by:
>          project :@react-native-camera-roll_camera-roll
> ```

Oddly enough, this solution seemed to work for me: https://github.com/react-native-cameraroll/react-native-cameraroll/issues/519#issuecomment-1674579963

**Comment by ViktorVojtek** [comment] 2023-10-19 20:25
Any updates on this?

**Comment by coralscherb** [comment] 2023-11-06 19:21
Hi I have a similar issue:

> Task :@react-native-camera-roll_camera-roll:generateReleaseRFile FAILED
Execution optimizations have been disabled for task ':@react-native-camera-roll_camera-roll:generateReleaseRFile' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/coralscherb/Documents/Projects/AwesomeProject/node_modules/@react-native-camera-roll/camera-roll/android/build/intermediates/local_only_symbol_list/release/R-def.txt'. Reason: Task ':@react-native-camera-roll_camera-roll:generateReleaseRFile' uses this output of task ':react-native-camera-roll_camera-roll:parseReleaseLocalResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/coralscherb/Documents/Projects/AwesomeProject/node_modules/@react-native-camera-roll/camera-roll/android/build/intermediates/packaged_manifests/release'. Reason: Task ':@react-native-camera-roll_camera-roll:generateReleaseRFile' uses this output of task ':react-native-camera-roll_camera-roll:processReleaseManifest' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :react-native-camera-roll_camera-roll:parseReleaseLocalResources
Execution optimizations have been disabled for task ':react-native-camera-roll_camera-roll:parseReleaseLocalResources' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/coralscherb/Documents/Projects/AwesomeProject/node_modules/@react-native-camera-roll/camera-roll/android/build/intermediates/packaged_res/release'. Reason: Task ':react-native-camera-roll_camera-roll:parseReleaseLocalResources' uses this output of task ':@react-native-camera-roll_camera-roll:packageReleaseResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':@react-native-camera-roll_camera-roll:generateReleaseRFile'.
> A failure occurred while executing com.android.build.gradle.internal.res.GenerateLibraryRFileTask$GenerateLibRFileRunnable
   > /Users/coralscherb/Documents/Projects/AwesomeProject/node_modules/@react-native-camera-roll/camera-roll/android/build/intermediates/local_only_symbol_list/release/R-def.txt

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

**Comment by Arjan-Zuidema** [comment] 2023-11-07 11:10
Can you try [v6.0.2](https://github.com/react-native-cameraroll/react-native-cameraroll/releases/tag/v6.0.2)? Some things for new arch were fixed that maybe fis this issue al well.

**Comment by ViktorVojtek** [comment] 2023-11-15 09:24
@Arjan-Zuidema just tried 6.0.2, here is the Error log after attempt to build app on android:


1: Task failed with an exception.
-----------
* What went wrong:
A problem was found with the configuration of task ':@react-native-camera-roll_camera-roll:compileDebugJavaWithJavac' (type 'JavaCompile').
  - Gradle detected a problem with the following location: '/Users/viktorvojtek/Projects/VirtualDomSK/app/node_modules/@react-native-camera-roll/camera-roll/android/build/generated/aidl_source_output_dir/debug/out'.
    
    Reason: Task ':@react-native-camera-roll_camera-roll:compileDebugJavaWithJavac' uses this output of task ':react-native-camera-roll_camera-roll:compileDebugAidl' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':react-native-camera-roll_camera-roll:compileDebugAidl' as an input of ':@react-native-camera-roll_camera-roll:compileDebugJavaWithJavac'.
      2. Declare an explicit dependency on ':react-native-camera-roll_camera-roll:compileDebugAidl' from ':@react-native-camera-roll_camera-roll:compileDebugJavaWithJavac' using Task#dependsOn.
      3. Declare an explicit dependency on ':react-native-camera-roll_camera-roll:compileDebugAidl' from ':@react-native-camera-roll_camera-roll:compileDebugJavaWithJavac' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.internal.execution.WorkValidationException: A problem was found with the configuration of task ':@react-native-camera-roll_camera-roll:compileDebugJavaWithJavac' (type 'JavaCompile').
  - Gradle detected a problem with the following location: '/Users/viktorvojtek/Projects/VirtualDomSK/app/node_modules/@react-native-camera-roll/camera-roll/android/build/generated/aidl_source_output_dir/debug/out'.
    
    Reason: Task ':@react-native-camera-roll_camera-roll:compileDebugJavaWithJavac' uses this output of task ':react-native-camera-roll_camera-roll:compileDebugAidl' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':react-native-camera-roll_camera-roll:compileDebugAidl' as an input of ':@react-native-camera-roll_camera-roll:compileDebugJavaWithJavac'.
      2. Declare an explicit dependency on ':react-native-camera-roll_camera-roll:compileDebugAidl' from ':@react-native-camera-roll_camera-roll:compileDebugJavaWithJavac' using Task#dependsOn.
      3. Declare an explicit dependency on ':react-native-camera-roll_camera-roll:compileDebugAidl' from ':@react-native-camera-roll_camera-roll:compileDebugJavaWithJavac' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
	at org.gradle.internal.execution.WorkValidationException$BuilderWithSummary.build(WorkValidationException.java:133)
	at org.gradle.internal.execution.WorkValidationException$BuilderWithSummary.get(WorkValidationException.java:115)
	at org.gradle.internal.execution.steps.ValidateStep.throwValidationException(ValidateStep.java:162)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:86)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:49)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:71)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:45)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNonEmptySources(SkipEmptyWorkStep.java:177)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:86)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:53)
	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
	at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:75)
	at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:41)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:32)
	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:287)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:21)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:42)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:31)
	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:64)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:135)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)

==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 29s
299 actionable tasks: 280 executed, 19 up-to-date

**Comment by ViktorVojtek** [comment] 2023-11-15 09:30
Update: As @mihailapuste commented on:

> > I am having the same issue after upgrade to ReactNative 0.72.4.
> > ```
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> > Execution failed for task ':@react-native-camera-roll_camera-roll:generateDebugRFile'.
> > > Could not resolve all files for configuration ':@react-native-camera-roll_camera-roll:debugCompileClasspath'.
> >    > Could not find com.facebook.react:react-native:0.72.4.
> >      Required by:
> >          project :@react-native-camera-roll_camera-roll
> > ```
> 
> Oddly enough, this solution seemed to work for me: [#519 (comment)](https://github.com/react-native-cameraroll/react-native-cameraroll/issues/519#issuecomment-1674579963)
> 
> > WOW, I removed configurations from android/settings.gradle and android/app/build.gradle and the build pass (but I'm having other error, I'm upgrading my app to 0.72.3).
> > Does your app works as expected?

Removing configurations from android/settings.gradle and android/app/build.gradle does help. But only after upgrading to v6.0.2. On previous versions this workaround doesn't work for me.

**Comment by Arjan-Zuidema** [comment] 2023-11-15 11:27
Ok. So I guess we can close the issue now there is a solution for the latest (6.0.2) version

**Closed** 2023-11-15 11:27 UTC
Labels: Waiting for repo
