### ISSUE TITLE
build error: The current character read is 'i' with an int value of 105

### ISSUE THREAD

**Issue by VEmpink** [react-native-cameraroll/react-native-cameraroll#509] opened 2023-06-28 04:40 UTC
Hello! I found an issue when i add this package to my project i've got error:
```
FAILURE: Build failed with an exception.

* Where:
Script '/Volumes/VEmpink/Projects/ubox/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 450

* What went wrong:
A problem occurred evaluating script.
> Calling `[node, /Volumes/VEmpink/Projects/ubox/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
  
  The current character read is 'i' with an int value of 105
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  info Run CLI with --verbose flag for more details.
  ^. Output: info Run CLI with --verbose flag for more details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDevelopmentDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Script '/Volumes/VEmpink/Projects/ubox/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 450

* What went wrong:
A problem occurred evaluating script.
> Calling `[node, /Volumes/VEmpink/Projects/ubox/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
  
  The current character read is 'i' with an int value of 105
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  info Run CLI with --verbose flag for more details.
  ^. Output: info Run CLI with --verbose flag for more details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at makeError (/Volumes/VEmpink/Projects/ubox/node_modules/execa/index.js:174:9)
    at /Volumes/VEmpink/Projects/ubox/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Volumes/VEmpink/Projects/ubox/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Volumes/VEmpink/Projects/ubox/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I try several solution like:
1. https://stackoverflow.com/questions/57744141/react-native-build-error-unable-to-determine-the-current-character-it-is-not-a
```
Solution 1: Delete the android/app/build folder and try to build again. It should work
Solution 2: run npm i --save @react-native-community/cli-platform-android
```

2. Delete `node_modules` and `yarn install` again
3. I've already checked `Androidmanifest.xml` it's all correctly
4. Deleting `app\build\intermediates\signing_config\debug\out\signing-config.json`

all solutions above only work when I do delete `node_modules` and `yarn install` again but the error will appear again if I run the second build (`yarn android`), which means I must delete `node_modules` and `yarn install` again every single time I want to develop/build the app

I've tried my both device which is Windows 11 and MacOS Ventura 13.3.1

my `package.json`:
```
{
  "name": "ubox",
  "version": "2.7.0",
  "private": true,
  "scripts": {
    "android": "ENVFILE=.env.development react-native run-android --variant=developmentDebug --appIdSuffix=dev",
    "android:production": "ENVFILE=.env.production react-native run-android --variant=productionDebug",
    "ios": "react-native run-ios --scheme 'uboxDev' --simulator='iPhone 11'",
    "ios:production": "react-native run-ios --simulator='iPhone 11'",
    "reinstall-packages": "rm -rf package-lock.json && rm -rf yarn.lock && rm -rf node_modules && yarn",
    "cleanup-android": "cd android && ./gradlew --stop && ./gradlew clean && cd ../",
    "cleanup-ios": "rm -rf ios/Podfile.lock && rm -rf ios/Pods && cd ios && pod repo update && pod update && pod install && cd ../",
    "build:android:development": "cd android && ENVFILE=.env.development ./gradlew bundleDevelopmentRelease && cd ../ && ENVFILE=.env.development react-native run-android --variant=developmentRelease --appIdSuffix=dev",
    "build:android:production": "cd android && ENVFILE=.env.production ./gradlew bundleProductionRelease && cd ../ && ENVFILE=.env.production react-native run-android --variant=productionRelease",
    "build:ios:development": "npx react-native run-ios --scheme 'uboxDev' --configuration Release --simulator='iPhone 11'",
    "build:ios:production": "npx react-native run-ios --configuration Release --simulator='iPhone 11'",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "build:tailwind": "tailwindcss --input input.css --output tailwind.css --no-autoprefixer && tailwind-rn",
    "dev:tailwind": "concurrently \"tailwindcss --input input.css --output tailwind.css --no-autoprefixer --watch\" \"tailwind-rn --watch\"",
    "postinstall": "patch-package",
    "upversion": "react-native-version --never-amend"
  },
  "dependencies": {
    "@eva-design/eva": "^2.1.1",
    "@gorhom/bottom-sheet": "^4",
    "@notifee/react-native": "^7.0.1",
    "@react-native-camera-roll/camera-roll": "^5.7.1",
    "@react-native-clipboard/clipboard": "^1.11.1",
    "@react-native-firebase/app": "15.6.0",
    "@react-native-firebase/crashlytics": "15.6.0",
    "@react-native-firebase/messaging": "15.6.0",
    "@react-native-google-signin/google-signin": "^8.0.0",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "@shopify/flash-list": "^1.2.1",
    "@tanstack/react-query": "^4.10.1",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "@ui-kitten/components": "^5.1.2",
    "@ui-kitten/date-fns": "^5.1.2",
    "@ui-kitten/eva-icons": "^5.1.2",
    "appcenter": "^4.4.5",
    "appcenter-analytics": "^4.4.5",
    "appcenter-crashes": "^4.4.5",
    "axios": "^0.27.2",
    "dayjs": "^1.11.5",
    "geolib": "^3.3.3",
    "lodash": "^4.17.21",
    "query-string": "^7.1.1",
    "react": "18.1.0",
    "react-hook-form": "^7.34.2",
    "react-native": "0.70.1",
    "react-native-animated-pagination-dots": "^0.1.73",
    "react-native-bootsplash": "^4.3.2",
    "react-native-camera-kit": "^13.0.0",
    "react-native-config": "1.4.11",
    "react-native-fast-image": "^8.6.3",
    "react-native-fbsdk-next": "^10.1.0",
    "react-native-fs": "^2.20.0",
    "react-native-geolocation-service": "^5.3.0",
    "react-native-gesture-handler": "^2.6.0",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-maps": "^1.3.1",
    "react-native-mmkv-storage": "^0.8.0",
    "react-native-permissions": "^3.6.1",
    "react-native-qrcode-styled": "^0.2.1",
    "react-native-reanimated": "2.10.0",
    "react-native-safe-area-context": "^4.3.3",
    "react-native-screens": "^3.16.0",
    "react-native-svg": "13.0.0",
    "react-native-toast-message": "^2.1.5",
    "react-native-webview": "^11.23.1",
    "semver": "^7.3.8",
    "socket.io": "^4.5.2",
    "socket.io-client": "^4.5.2",
    "tailwind-rn": "^4.2.0",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^26.0.23",
    "@types/lodash": "^4.14.184",
    "@types/react-native": "^0.69.3",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.29.0",
    "@typescript-eslint/parser": "^5.35.1",
    "babel-jest": "^26.6.3",
    "babel-plugin-import": "^1.13.5",
    "babel-plugin-module-resolver": "^4.1.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "concurrently": "^7.4.0",
    "eslint": "^8.22.0",
    "eslint-import-resolver-typescript": "^3.5.0",
    "eslint-plugin-es": "^4.1.0",
    "eslint-plugin-import": "^2.26.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.72.1",
    "patch-package": "^6.5.0",
    "postcss": "^8.4.17",
    "postinstall-postinstall": "^2.1.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-version": "^4.0.0",
    "react-test-renderer": "18.1.0",
    "tailwindcss": "^3.1.8",
    "typescript": "^4.7.4"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
```

**Comment by Arjan-Zuidema** [comment] 2023-06-28 06:32
Hi!

What makes you think the error is related to this package? I am unable to reproduce your error. Not in the example nor an other project I am working on. Also the error does not mention anything about react-native-cameraroll

**Comment by LamQuyet** [comment] 2023-06-28 07:58
when i install react-native-image-crop-picker I also got the same error

**Comment by Arjan-Zuidema** [comment] 2023-06-28 09:55
Seems like this is not an issue with react-native-cameraroll but rather something in the react-native CLI. Closing this for now. 
Feel free to reopen when you have more info about the error being related to this package.

**Closed by Arjan-Zuidema** 2023-06-28 09:55 UTC

**Comment by VEmpink** [comment] 2023-06-28 15:13
I finally fixed it for my both device Windows 11 and MacOS Ventura

i just downgrade from `"@react-native-camera-roll/camera-roll": "^5.7.1"` to `"@react-native-camera-roll/camera-roll": "5.3.0"`

**Comment by douugdev** [comment] 2023-06-28 18:53
> Seems like this is not an issue with react-native-cameraroll but rather something in the react-native CLI. Closing this for now.
Feel free to reopen when you have more info about the error being related to this package.

For some reason it seems to be related to this project, I am facing the exact same issue using react native `0.70.6` and @react-native-camera-roll/camera-roll `5.7.1`, downgrading to `5.6.1` already resumes working the android build again. I assume it has to do with the RN `0.73` support added a few days ago.

**Comment by joshuapinter** [comment] 2023-07-11 16:47
@douugdev Same here. Downgraded to 5.6.1 and the issue went away. I'm not sure why this was closed as "completed". I don't see anything in the commit history that would have fixed this issue. If their support for RN 0.73 requires the use of 0.73, then this should have been a major release, indicating backward-incompt changes.

**Comment by shockdesign** [comment] 2024-05-02 10:36
Since it isn't mentioned here, the error occurs due to the package name disappearing from the AndroidManifest.xml which seems to be removed with  the support for RN 0.73... it needs to stay for backwards compatibility.
